### ISSUE TITLE
Call new method on retry

### ISSUE THREAD

**Issue by derylspielman** [jhalterman/recurrent#1]
I am sending bulk e-mails via Spring's JavaMailSenderImpl class. When there is a failure a MailSendException is thrown containing the failed messages.  I would like to retry only those messages that are found within the exception and in a sense recursively keep doing so until finally no exception is thrown or the retry policy has failed. Do you think this is possible with this framework?

**Comment by jhalterman** [comment]
That's an interesting scenario. Basically, we would need to modify the arguments passed to `JavaMailSenderImpl.send` (or whatever) for each retry based on the contents of `MailSendException`. There's currently no way to do this with Recurrent since Recurrent just re-runs a `Callable` or `Runnable`. It could be possible to swap in a new `Callable` or `Runnable`, but modifying the actual arguments would require a different approach, more along the lines of another library, [Sarge](https://github.com/jhalterman/sarge).

What I'd like to do instead is support this sort of use case via Recurrent's [retry tracking](https://github.com/jhalterman/recurrent#retry-tracking), where you can manually perform retries within a loop but still use Recurrent to manage the policy and track retries for you. Ex:


```
Collection<Object> messages = ....
RetryStats stats = new RetryStats(retryPolicy);
while (stats.canRetry() && !messages.isEmpty()) {
  try {
    mailSender.send(messages);
  } catch (MailSendException e) {
    messages = e.getFailedMessages().values();
  }
}
```

This sort of thing isn't possible right now, but I just wanted to give you an idea of what I'm thinking. Thoughts?

**Comment by derylspielman** [comment]
I am able to achieve this through nurkiewicz async retry framework https://github.com/nurkiewicz/async-retry as you get the last Throwable inside a context object provided to you in the block of code retrying. I haven't tested this yet though.

**Comment by jhalterman** [comment]
What does the approach look like with async-retry? What do you think of the suggested API?

**Comment by jhalterman** [comment]
I just pushed an approach for this. https://github.com/jhalterman/recurrent#invocation-tracking

The Invocation also makes the [last failure available](http://jodah.net/recurrent/javadoc/net/jodah/recurrent/Invocation.html#getLastFailure--).
